"""fix duplicates in steam_user

Revision ID: 1ee195fdf684
Revises: 605334246c98
Create Date: 2025-05-10 19:24:30.372812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee195fdf684'
down_revision = '605334246c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_user', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=200), nullable=False))

    # ### end Alembic commands ###
