"""rename image to avatar_url

Revision ID: 3a0217339cea
Revises: 93840f94655b
Create Date: 2025-05-04 20:11:56.294978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a0217339cea'
down_revision = '93840f94655b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=200), nullable=False))
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
