from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5a68c6b0ff4a'
down_revision = '241d1ab8d0ae'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_steam_user_id_user',  # Foreign key constraint name
            'user',                   # Reference table
            ['id'],                   # Column in 'steam_user'
            ['id']                    # Column in 'user'
        )

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_steam_user_id_user', type_='foreignkey')
        batch_op.drop_column('id')

    op.create_table('_alembic_tmp_steam_user',
    sa.Column('steam_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=200), nullable=False),
    sa.Column('image', sa.VARCHAR(length=200), nullable=False),
    sa.ForeignKeyConstraint(['steam_id'], ['user.steam_id'], name='fk_steam_user_steam_id_user'),  # Foreign key constraint name
    sa.PrimaryKeyConstraint('steam_id')
    )
    # ### end Alembic commands ###
