"""rename image to avatar_url

Revision ID: 93840f94655b
Revises: 5a68c6b0ff4a
Create Date: 2025-05-04 20:11:14.619864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93840f94655b'
down_revision = '5a68c6b0ff4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=200), nullable=False))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
