"""Make title nullable with default value

Revision ID: 93a49de9d64e
Revises: d558af38396e
Create Date: 2025-05-11 12:14:07.997111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a49de9d64e'
down_revision = 'd558af38396e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_cards', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
