"""created share_id for shared_collections

Revision ID: 9a2edfcf2b79
Revises: caf477de5c91
Create Date: 2025-05-11 16:04:12.801099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2edfcf2b79'
down_revision = 'caf477de5c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_id', sa.Integer(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_collections', schema=None) as batch_op:
        batch_op.drop_column('share_id')

    # ### end Alembic commands ###
