"""avatar_url to image

Revision ID: a271f5cf771e
Revises: 32db5bd806eb
Create Date: 2025-05-10 20:00:58.935446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a271f5cf771e'
down_revision = '32db5bd806eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=False))
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('steam_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
