"""add shared_collections, saved_collections and saved_cards

Revision ID: afc43da21ed5
Revises: a271f5cf771e
Create Date: 2025-05-12 14:16:49.894141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc43da21ed5'
down_revision = 'a271f5cf771e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_collections',
    sa.Column('saved_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('steam_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['steam_id'], ['steam_user.steam_id'], ),
    sa.PrimaryKeyConstraint('saved_id')
    )
    op.create_table('saved_cards',
    sa.Column('card_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('saved_id', sa.Integer(), nullable=False),
    sa.Column('card', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['saved_id'], ['saved_collections.saved_id'], ),
    sa.PrimaryKeyConstraint('card_no')
    )
    op.create_table('shared_collections',
    sa.Column('share_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('saved_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['saved_id'], ['saved_collections.saved_id'], ),
    sa.PrimaryKeyConstraint('share_id')
    )
    op.drop_table('_alembic_tmp_steam_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_steam_user',
    sa.Column('steam_id', sa.INTEGER(), nullable=False),
    sa.Column('avatar_url', sa.VARCHAR(length=200), nullable=False),
    sa.Column('username', sa.VARCHAR(length=200), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('n_games_owned', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('steam_id')
    )
    op.drop_table('shared_collections')
    op.drop_table('saved_cards')
    op.drop_table('saved_collections')
    # ### end Alembic commands ###
