"""created SharedCollection, SavedCollection and SavedCards tables

Revision ID: caf477de5c91
Revises: a271f5cf771e
Create Date: 2025-05-11 15:20:25.988476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf477de5c91'
down_revision = 'a271f5cf771e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_cards',
    sa.Column('card_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('saved_id', sa.Integer(), nullable=False),
    sa.Column('card', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['saved_id'], ['saved_collections.saved_id'], ),
    sa.PrimaryKeyConstraint('card_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_cards')
    # ### end Alembic commands ###
