"""add save cards table

Revision ID: d558af38396e
Revises: a271f5cf771e
Create Date: 2025-05-11 11:27:22.169859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd558af38396e'
down_revision = 'a271f5cf771e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_cards',
    sa.Column('saved_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('steam_id', sa.Integer(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['steam_id'], ['steam_user.steam_id'], ),
    sa.PrimaryKeyConstraint('saved_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_cards')
    # ### end Alembic commands ###
